os: linux
dist: trusty
language: cpp
compiler: gcc

matrix:
  exclude:
    compiler: gcc

  include:

    # GCC
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - libboost1.55-dev
            - libboost-python1.55-dev
            - graphviz
      compiler: gcc
      env:
        - COMPILER_EVAL="export CC=gcc-4.9 && export CXX=g++-4.9"
        - ROOT_VERSION=6.06.02 CMAKE_VERSION=3.6.1 PYTHON=TRUE

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - libboost1.55-dev
            - libboost-python1.55-dev
            - graphviz
      compiler: gcc
      env:
        - COMPILER_EVAL="export CC=gcc-4.9 && export CXX=g++-4.9"
        - ROOT_VERSION=6.06.02 CMAKE_VERSION=3.5.2 PYTHON=TRUE

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - libboost1.55-dev
            - libboost-python1.55-dev
            - graphviz
      compiler: gcc
      env:
        - COMPILER_EVAL="export CC=gcc-4.9 && export CXX=g++-4.9"
        - ROOT_VERSION=6.06.02 CMAKE_VERSION=3.2.1 PYTHON=TRUE

    # GCC, old ROOT release
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - libboost1.55-dev
            - libboost-python1.55-dev
            - graphviz
      compiler: gcc
      env:
        - COMPILER_EVAL="export CC=gcc-4.9 && export CXX=g++-4.9"
        - ROOT_VERSION=5.34.25 CMAKE_VERSION=3.6.1 PYTHON=TRUE

    # GCC, without python bindings
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - libboost1.55-dev
            - graphviz
      compiler: gcc
      env:
        - COMPILER_EVAL="export CC=gcc-4.9 && export CXX=g++-4.9"
        - ROOT_VERSION=6.06.02 CMAKE_VERSION=3.6.1 PYTHON=FALSE

    # clang
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libboost1.55-dev
            - libboost-python1.55-dev
            - graphviz
      compiler: clang
      env:
        - COMPILER_EVAL="export CC=clang-4.0 && export CXX=clang++-4.0"
        - ROOT_VERSION=6.06.02 CMAKE_VERSION=3.6.1 PYTHON=TRUE

before_install:
  - eval "${COMPILER_EVAL}" 
  - ./travis/decrypt_key.sh
  - pip install --user cpp-coveralls

install:
  - eval "${COMPILER_EVAL}" 
  - source travis/get-cmake.sh
  - source travis/get-root.sh
  - source travis/get-lhapdf.sh
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then source travis/get-doxygen.sh; fi

before_script:
  - eval "${COMPILER_EVAL}" 
  - mkdir build
  - cd build
  - cmake .. -DTESTS=ON -DCOVERAGE=ON -DPYTHON_BINDINGS=ON -DCMAKE_BUILD_TYPE=Debug

script:
  - make -j2 && ./run_tests.sh

after_success:
  - coveralls -e 'external/' --gcov-options '\-lp' -E '.*CMakeCXXCompilerId\.cpp' -E '.*CMakeCCompilerId\.c' -E '.*feature_tests\.c.*' -E '.*MatrixElements/.*' -E '.*/tests/*.' -r .. &> /dev/null;
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then ./make_docs.sh; fi
